
Neos:
  GoogleAnalytics:
    enableTracking: true
    sites:
      ## All site specific settings are indexed by site node name
      site:
        analytics:
          id: '%env:GOOGLE_ANALYTICS_TRACKING_CODE%'
        profileId: '%env:GOOGLE_ANALYTICS_PROFILE_ID%'
