
GesagtGetan:
  CookieDialogue:
    findQuery: '[uriPathSegment=imprint][uriPathSegment=impressum]'
    javascript:
      # Set to `Storage` or `Cookie`
      implementation: Storage
      callback:
        accept: null
        decline: null
    css:
      container: 'font-size:12px;background:rgba(0,0,0,0.7);color:#fff;padding:1rem  0.5rem 0'
      button:
        normal: 'color:#fff;border:1px solid #fff;background:transparent;margin-top: 0.5rem'
